"use client";
import React, { useState, useEffect } from 'react';
import { fetchWithAuth } from '@/utils/api';
import { Bot, MapPin, Calendar, Clock, Loader2, Search, CheckCircle2, Phone, ArrowLeft, Menu } from 'lucide-react';
import AdminSidebar from '@/components/admin/AdminSidebar';
import { useRouter } from 'next/navigation';

interface Lead {
  _id: string;
  name: string;
  phone: string;
  city: string;
  preferredTime: string;
  interest: string;
  status: string;
  createdAt: string;
}

export default function LeadsPage() {
  const [leads, setLeads] = useState<Lead[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const router = useRouter();

  useEffect(() => {
    fetchLeads();
  }, []);

  const fetchLeads = async () => {
    try {
      setLoading(true);
      const data = await fetchWithAuth('/leads');
      setLeads(data);
    } catch (error: any) {
      console.error(error);
      alert('Failed to load leads');
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (id: string, status: string) => {
    try {
      await fetchWithAuth(`/leads/${id}/status`, {
        method: 'PATCH',
        body: JSON.stringify({ status })
      });
      alert('Status updated');
      fetchLeads();
    } catch (error: any) {
       alert('Failed to update status');
    }
  };

  const filteredLeads = leads.filter(l => 
    l.name.toLowerCase().includes(search.toLowerCase()) || 
    l.city.toLowerCase().includes(search.toLowerCase()) ||
    l.phone.includes(search)
  );

  return (
    <div className="flex min-h-screen bg-bg-base font-inter">
      <AdminSidebar isOpen={isSidebarOpen} onClose={() => setIsSidebarOpen(false)} />
      
      <main className="flex-1 lg:ml-[280px] min-w-0 transition-all duration-300">
        <div className="p-4 md:p-8 space-y-8">
           <div className="flex flex-col md:flex-row justify-between md:items-center gap-4">
              <div className="flex items-center gap-4">
                <button onClick={() => setIsSidebarOpen(true)} className="lg:hidden p-2 rounded-xl bg-bg-muted hover:bg-bg-surface">
                  <Menu className="h-5 w-5" />
                </button>
                <button onClick={() => router.back()} className="p-2 bg-bg-muted hover:bg-bg-surface rounded-xl transition-all mr-2">
                  <ArrowLeft className="h-5 w-5 text-fg-primary" />
                </button>
                <div>
                  <h1 className="text-3xl font-black text-fg-primary tracking-tight">Chatbot Leads</h1>
                  <p className="text-fg-muted font-medium mt-1">Manage leads generated by the AI assistant.</p>
                </div>
              </div>
              
              <div className="relative w-full md:w-72">
                 <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-fg-muted" />
                 <input 
                   type="text" 
                   placeholder="Search by name, city, phone..." 
                   value={search}
                   onChange={(e) => setSearch(e.target.value)}
                   className="w-full bg-bg-surface border border-border-base rounded-xl pl-10 pr-4 py-2 text-sm focus:border-blue-500 focus:outline-none"
                 />
              </div>
           </div>

       {loading ? (
          <div className="flex justify-center py-20"><Loader2 className="w-8 h-8 animate-spin text-blue-500" /></div>
       ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
             {filteredLeads.map(lead => (
               <div key={lead._id} className="bg-bg-surface rounded-2xl border border-border-base p-6 hover:border-border-strong transition-colors shadow-sm relative overflow-hidden group">
                  <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-cyan-400 opacity-50 group-hover:opacity-100 transition-opacity"></div>
                  
                  <div className="flex justify-between items-start mb-6">
                    <div className="flex items-center gap-3">
                       <div className="w-10 h-10 bg-blue-600/10 rounded-full flex items-center justify-center text-blue-500">
                         <Bot className="w-5 h-5" />
                       </div>
                       <div>
                         <h3 className="font-bold text-fg-primary">{lead.name}</h3>
                         <p className="text-[10px] text-fg-muted font-black tracking-widest uppercase">{lead.interest}</p>
                       </div>
                    </div>
                    
                    <select 
                      value={lead.status}
                      onChange={(e) => updateStatus(lead._id, e.target.value)}
                      className={`text-xs font-bold px-3 py-1 rounded-full border cursor-pointer outline-none ${
                        lead.status === 'new' ? 'bg-amber-500/10 text-amber-500 border-amber-500/20' : 
                        lead.status === 'contacted' ? 'bg-blue-500/10 text-blue-500 border-blue-500/20' :
                        lead.status === 'converted' ? 'bg-green-500/10 text-green-500 border-green-500/20' :
                        'bg-gray-500/10 text-gray-500 border-gray-500/20'
                      }`}
                    >
                       <option value="new">New Lead</option>
                       <option value="contacted">Contacted</option>
                       <option value="converted">Converted</option>
                       <option value="closed">Closed/Lost</option>
                    </select>
                  </div>
                  
                  <div className="space-y-3 mb-6">
                     <div className="flex items-center gap-3 text-sm text-fg-muted">
                        <Phone className="w-4 h-4 text-fg-dim" />
                        <a href={`tel:${lead.phone}`} className="hover:text-blue-500 font-medium">{lead.phone}</a>
                     </div>
                     <div className="flex items-center gap-3 text-sm text-fg-muted">
                        <MapPin className="w-4 h-4 text-fg-dim" />
                        <span className="font-medium">{lead.city}</span>
                     </div>
                     <div className="flex items-center gap-3 text-sm text-fg-muted">
                        <Clock className="w-4 h-4 text-fg-dim" />
                        <span className="font-medium">Prefers: {lead.preferredTime}</span>
                     </div>
                     <div className="flex items-center gap-3 text-sm text-fg-muted">
                        <Calendar className="w-4 h-4 text-fg-dim" />
                        <span className="font-medium">{new Date(lead.createdAt).toLocaleDateString()} at {new Date(lead.createdAt).toLocaleTimeString()}</span>
                     </div>
                  </div>

                  {lead.status === 'converted' && (
                    <div className="absolute -bottom-4 -right-4 text-green-500/10">
                       <CheckCircle2 className="w-32 h-32" />
                    </div>
                  )}
               </div>
             ))}
             
             {filteredLeads.length === 0 && (
                <div className="col-span-full py-20 text-center border-2 border-dashed border-border-base rounded-3xl">
                   <p className="text-fg-muted font-medium">No leads found.</p>
                </div>
             )}
           </div>
        )}
      </div>
     </main>
    </div>
  );
}
